# Generated by Django 4.2.17 on 2025-11-20 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='出版社')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='封面图片')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='总册数')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='可借册数')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='书架位置')),
                ('status', models.CharField(choices=[('available', '可借阅'), ('borrowed', '已借出'), ('maintenance', '维护中'), ('lost', '丢失')], default='available', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
            },
        ),
    ]
