# Generated by Django 4.2.17 on 2025-12-10 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_alter_book_category'),
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='预约时间')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('available', '可借阅'), ('cancelled', '已取消'), ('completed', '已完成'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='预约状态')),
                ('priority', models.IntegerField(choices=[(1, '普通'), (2, '优先'), (3, '高优先级')], default=1, verbose_name='优先级')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='是否已发送通知')),
                ('notification_date', models.DateTimeField(blank=True, null=True, verbose_name='通知时间')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='预约过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '图书预约',
                'verbose_name_plural': '图书预约',
                'ordering': ['priority', 'reservation_date'],
                'indexes': [models.Index(fields=['book', 'status', 'priority'], name='borrowing_b_book_id_8a7542_idx'), models.Index(fields=['user', 'status'], name='borrowing_b_user_id_03e740_idx'), models.Index(fields=['reservation_date'], name='borrowing_b_reserva_024fc9_idx'), models.Index(fields=['expiry_date'], name='borrowing_b_expiry__b7cd52_idx')],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
